name: Winget

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.set_output.outputs.upload_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Echo token
      run: echo ${{ github.event.release.tag_name || github.ref_name }}
    - name: Install Cargo Bins
      uses: cargo-bins/cargo-binstall@main
    - name: Install Komac
      run: cargo binstall komac -y
    - name: Dry Run
      run: |
        komac update HonhimW.Ratisui \
            --version "0.6.0" \
            --urls "https://github.com/honhimW/ratisui/releases/download/0.6.0/ratisui-windows-amd64.zip" \
            --dry-run
    # - name: WinGet Releaser
    #   # You may pin to the exact commit or the version.
    #   # uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e
    #   uses: vedantmgoyal9/winget-releaser@v2
    #   with:
    #     # The PackageIdentifier of the package (case-sensitive).
    #     identifier: HonhimW.Ratisui
    #     # The maximum number of versions to keep in WinGet Community Repository (Default: 0 - no limit)
    #     max-versions-to-keep: 3
    #     # GitHub token to create pull request on Windows Package Manager Community Repository.
    #     token: ${secrets.WINGET_TOKEN}
          
